Revert "Child 1"
jaxinye/UMSITest pull request #4
Opened 2018-08-22 14:25 UTC by jaxinye

Reverts jaxinye/UMSITest#1

2018-08-22 14:26 UTC, ghost requested changes

2018-08-22 14:26 UTC, gitprojecttest1 commented on .gitmodules
> -	path = Python-100-Days
revert

2018-08-22 14:35 UTC, ghost approved these changes

2018-08-22 14:35 UTC, ghost submitted a review, later dismissed
ccccc

2018-08-22 14:35 UTC, gitprojecttest1 commented on .gitmodules
> -[submodule "Python-100-Days"]
ffff

2018-08-22 14:44 UTC, jaxinye commented on .gitmodules
> -[submodule "Python-100-Days"]
jaxinye

2018-09-05 18:55 UTC, jaxinye commented
ggg

2018-09-06 18:49 UTC, ghost requested changes
comment

2018-09-06 18:53 UTC, ghost requested changes
comment2

2018-09-06 18:53 UTC, gitprojecttest1 commented on child1.py
> -    html = urlopen("https://github.com/trending")
comment1

2018-09-12 04:11 UTC, closed without merging